import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    // width: 326px;
    // height: 326px;

    background: white;
    in property <[int]> amplitudes: [];
    // todo:
    // Want a wave form visualization. The kind that is a horizontal chart representing the amplitude
    // - Horizontal layout
    // - Line height is the amplitude
    Rectangle {
        border-color: lime;
        border-width: 2px;
        HorizontalLayout {
            height: 100px;
            alignment: center;

            for h in amplitudes: Rectangle {
                background: red;
                width: 4px;
                height: h * 1px;
                y: (parent.height / 2) - (self.height / 2);
            }
        }
    }
}
